### ISSUE TITLE
Pick any with textbox with string answer throws error

### ISSUE THREAD

**Issue by jdzak** [NUARIG/surveyor#154]
Given the following survey, if you click a checkbox you will see the stack trace below.

<pre>
survey "Kitchen Sink survey" do
  section "Basic questions" do
    q "Choose your favorite utensils and enter frequency of use (daily, weekly, monthly, etc...)", :pick => :any
    a "spoon", :string
    a "fork", :string
    a "knife", :string
    a :other, :string
  end
end
</pre>

<pre>
ActiveRecord::RecordNotFound (Couldn't find all Answers with IDs (0,242) (found 1 results, but was looking for 2)):
  /Users/johndzak/Code/nubic-surveyor/lib/surveyor/models/response_methods.rb:23:in `applicable_attributes'
  /Users/johndzak/Code/nubic-surveyor/lib/surveyor/models/response_set_methods.rb:29:in `reject_or_destroy_blanks'
  /Users/johndzak/Code/nubic-surveyor/lib/surveyor/models/response_set_methods.rb:28:in `each_pair'
  /Users/johndzak/Code/nubic-surveyor/lib/surveyor/models/response_set_methods.rb:28:in `reject_or_destroy_blanks'
  /Users/johndzak/Code/nubic-surveyor/lib/surveyor/surveyor_controller_methods.rb:65:in `update'
  /Users/johndzak/Code/nubic-surveyor/lib/surveyor/surveyor_controller_methods.rb:64:in `update'
  haml (3.1.1) vendor/sass/lib/sass/./sass/plugin/rack.rb:54:in `call'
  /Users/johndzak/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /Users/johndzak/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /Users/johndzak/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /Users/johndzak/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/webrick/server.rb:162:in `start'
  /Users/johndzak/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /Users/johndzak/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/webrick/server.rb:95:in `start'
  /Users/johndzak/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /Users/johndzak/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/webrick/server.rb:92:in `start'
  /Users/johndzak/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /Users/johndzak/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/webrick/server.rb:82:in `start'
</pre>

**Comment by jdzak** [comment]
This was introduced in this commit.

https://github.com/jdzak/surveyor/commit/b280e0f57127d009c717c8837425d25782a7fecb

**Comment by jdzak** [comment]
Pull request is #156.
