### ISSUE TITLE
UTF-8 Encoding breaks rake surveyor FILE="file_name.rb"

### ISSUE THREAD

**Issue by allenwyma** [NUARIG/surveyor#164]
Have tried using both # encoding: utf-8 and # coding: utf-8 shebangs on the top of my survey file, but it still dies. Im guessing this needs to be done somewhere in the code, but not quite sure. If need be, i can try to track it down, just reporting this issue for right now.

**Comment by ouyangzhiping** [comment]
same question

when I write survey in chinese, and run : rake surveyor FILE=surveys/chinese.rb --trace

find:

```
incompatible encoding regexp match (Windows-31J regexp with UTF-8 string)
```

**Comment by ouyangzhiping** [comment]
this is my survey file:

```
# encoding: utf-8
survey "青少年人际关系问卷" do

section "Basic questions" do

# Grids are useful for repeated questions with the same set of answers, which are specified before the questions
grid "第二部分：以下列出了一些描述。请您根据自己的实际情况作答。如果“非常不像我”，请选“1”，如果“非常像我”，请选“5”，以此类推。" do
  a "1"
  a "2"
  a "3"
  a "4"
  a "5"
  q "我常常想出新的有趣的点子", :pick => :one
  q "我比同龄的其他孩子更有想象力", :pick => :one
  q "即使一个人独处，我也不会觉得无聊", :pick => :one
end

end

end
```

rake -t :

```
rake surveyor FILE=surveys/chinese.rb -t
** Invoke surveyor (first_time)
** Invoke surveyor:parse (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute surveyor:parse
--- Parsing /Users/ouyang/dev/learn/ruby/surveyor/surveys/chinese.rb ---

survey survey_section question_group answer answer answer answer answer question rake aborted!
incompatible encoding regexp match (Windows-31J regexp with UTF-8 string)
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:20:in `instance_eval'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/common.rb:18:in `to_normalized_string'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/models/question_methods.rb:40:in `default_args'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/models/question_methods.rb:33:in `initialize'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/activerecord-3.2.1/lib/active_record/reflection.rb:183:in `new'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/activerecord-3.2.1/lib/active_record/reflection.rb:183:in `build_association'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/activerecord-3.2.1/lib/active_record/associations/association.rb:233:in `build_record'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/activerecord-3.2.1/lib/active_record/associations/collection_association.rb:112:in `build'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/activerecord-3.2.1/lib/active_record/associations/collection_proxy.rb:46:in `build'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:137:in `parse_and_build'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:35:in `method_missing'
(eval):13:in `block (3 levels) in parse'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:39:in `instance_eval'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:39:in `method_missing'
(eval):7:in `block (2 levels) in parse'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:39:in `instance_eval'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:39:in `method_missing'
(eval):4:in `block in parse'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:39:in `instance_eval'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:39:in `method_missing'
(eval):2:in `parse'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:20:in `instance_eval'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:20:in `parse'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/surveyor/parser.rb:11:in `parse'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/surveyor-0.21.0/lib/tasks/surveyor_tasks.rake:11:in `block (2 levels) in <top (required)>'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/ouyang/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/Users/ouyang/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/bin/rake:19:in `load'
/Users/ouyang/.rvm/gems/ruby-1.9.2-p290@rails31/bin/rake:19:in `<main>'
Tasks: TOP => surveyor => surveyor:parse
```
