### ISSUE TITLE
uninitialized constant AddDisplayTypeToAnswers::Answer

### ISSUE THREAD

**Issue by damselem** [NUARIG/surveyor#190]
I got this error after executing the following commands:

sudo gem install rails -v 2.3.9
rails test_app
cd test_app
bundle init
bundle install
rake db:migrate

The full error trace:

(in /Users/daniel.amselem/Personal/cisvisa)
*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute db:migrate
==  CreateSurveys: migrating ==================================================
-- create_table(:surveys)
   -> 0.0032s
==  CreateSurveys: migrated (0.0043s) =========================================

==  CreateSurveySections: migrating ===========================================
-- create_table(:survey_sections)
   -> 0.0027s
==  CreateSurveySections: migrated (0.0028s) ==================================

==  CreateQuestions: migrating ================================================
-- create_table(:questions)
   -> 0.0037s
==  CreateQuestions: migrated (0.0040s) =======================================

==  CreateQuestionGroups: migrating ===========================================
-- create_table(:question_groups)
   -> 0.0032s
==  CreateQuestionGroups: migrated (0.0034s) ==================================

==  CreateAnswers: migrating ==================================================
-- create_table(:answers)
   -> 0.0051s
==  CreateAnswers: migrated (0.0054s) =========================================

==  CreateResponseSets: migrating =============================================
-- create_table(:response_sets)
   -> 0.0708s
==  CreateResponseSets: migrated (0.0710s) ====================================

==  CreateResponses: migrating ================================================
-- create_table(:responses)
   -> 0.0033s
==  CreateResponses: migrated (0.0037s) =======================================

==  CreateDependencies: migrating =============================================
-- create_table(:dependencies)
   -> 0.0015s
==  CreateDependencies: migrated (0.0017s) ====================================

==  CreateDependencyConditions: migrating =====================================
-- create_table(:dependency_conditions)
   -> 0.0028s
==  CreateDependencyConditions: migrated (0.0029s) ============================

==  CreateValidations: migrating ==============================================
-- create_table(:validations)
   -> 0.0015s
==  CreateValidations: migrated (0.0016s) =====================================

==  CreateValidationConditions: migrating =====================================
-- create_table(:validation_conditions)
   -> 0.0079s
==  CreateValidationConditions: migrated (0.0081s) ============================

==  AddDisplayOrderToSurveys: migrating =======================================
-- add_column(:surveys, :display_order, :integer)
   -> 0.0008s
==  AddDisplayOrderToSurveys: migrated (0.0009s) ==============================

==  AddCorrectAnswerIdToQuestions: migrating ==================================
-- add_column(:questions, :correct_answer_id, :integer)
   -> 0.0011s
==  AddCorrectAnswerIdToQuestions: migrated (0.0016s) =========================

==  AddIndexToResponseSets: migrating =========================================
-- add_index(:response_sets, :access_code, {:name=>"response_sets_ac_idx"})
   -> 0.0011s
==  AddIndexToResponseSets: migrated (0.0012s) ================================

==  AddIndexToSurveys: migrating ==============================================
-- add_index(:surveys, :access_code, {:name=>"surveys_ac_idx"})
   -> 0.0010s
==  AddIndexToSurveys: migrated (0.0013s) =====================================

==  AddUniqueIndicies: migrating ==============================================
-- remove_index(:response_sets, {:name=>"response_sets_ac_idx"})
   -> 0.0015s
-- add_index(:response_sets, :access_code, {:unique=>true, :name=>"response_sets_ac_idx"})
   -> 0.0005s
-- remove_index(:surveys, {:name=>"surveys_ac_idx"})
   -> 0.0010s
-- add_index(:surveys, :access_code, {:unique=>true, :name=>"surveys_ac_idx"})
   -> 0.0005s
==  AddUniqueIndicies: migrated (0.0039s) =====================================

==  AddSectionIdToResponses: migrating ========================================
-- add_column(:responses, :survey_section_id, :integer)
   -> 0.0009s
-- add_index(:responses, :survey_section_id)
   -> 0.0005s
==  AddSectionIdToResponses: migrated (0.0015s) ===============================

==  AddDefaultValueToAnswers: migrating =======================================
-- add_column(:answers, :default_value, :string)
   -> 0.0010s
==  AddDefaultValueToAnswers: migrated (0.0011s) ==============================

==  AddApiIds: migrating ======================================================
-- add_column(:surveys, :api_id, :string)
   -> 0.0009s
-- add_column(:questions, :api_id, :string)
   -> 0.0013s
-- add_column(:answers, :api_id, :string)
   -> 0.0013s
==  AddApiIds: migrated (0.0043s) =============================================

==  AddDisplayTypeToAnswers: migrating ========================================
-- add_column(:answers, :display_type, :string)
   -> 0.0010s
rake aborted!
An error has occurred, this and all later migrations canceled:

uninitialized constant AddDisplayTypeToAnswers::Answer
/Library/Ruby/Gems/1.8/gems/activesupport-2.3.9/lib/active_support/dependencies.rb:131:in `const_missing'
./db/migrate//20110727140765_add_display_type_to_answers.rb:4:in`up_without_benchmarks'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:282:in `send'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:282:in`migrate'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/benchmark.rb:293:in `measure'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:282:in`migrate'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:365:in `__send__'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:365:in`migrate'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:491:in `migrate'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:565:in`call'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:565:in `ddl_transaction'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in`transaction'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/transactions.rb:182:in `transaction'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:565:in`ddl_transaction'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:490:in `migrate'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:477:in`each'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:477:in `migrate'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:401:in`up'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.9/lib/active_record/migration.rb:383:in `migrate'
/Library/Ruby/Gems/1.8/gems/rails-2.3.9/lib/tasks/databases.rake:112
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`call'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`each'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in `load'
/usr/bin/rake:19

Is there anything I'm missing?

**Comment by damselem** [comment]
Submited a pull request with a working solution.

https://github.com/NUBIC/surveyor/pull/191
