### ISSUE TITLE
Grid question responses fail to store via JavaScript

### ISSUE THREAD

**Issue by rsutphin** [NUARIG/surveyor#339]
In the current master, grid question responses do not store properly. You can see this in the testbed app:
1. Generate the testbed and load the kitchen sink survey in it
2. Start the testbed server
3. Take the KS survey
4. Answer any question in the first section 
5. Go to the second section
6. Select any option for the "Tell us how often do you cover these each day" question
7. Refresh the page

Expected: the response you selected for the grid question should be preserved
Actual: the response is not preserved

I've observed this with Surveyor deployed in Rails 3.2.6 interacting with Surveyor in Firefox 13.0.1 and Safari 5.1.7. 

There is a cucumber feature for grid questions; it passes both as-is and if it is executed in Selenium, so it may be something specific to the way the kitchen sink survey is set up.

**Comment by rsutphin** [comment]
There was an earlier bug about grid questions: #161.

**Comment by rsutphin** [comment]
Examination with Firebug shows that the AJAX PUT attempting to store the response errors out. The server-side exception is:

```
RuntimeError (Called id for nil, which would mistakenly be 4 -- if you really wanted the id of nil, use object_id):
  /Users/rsutphin/ruby/surveyor/lib/surveyor/surveyor_controller_methods.rb:104:in `block (3 levels) in update'
  /Users/rsutphin/ruby/surveyor/lib/surveyor/surveyor_controller_methods.rb:102:in `each'
  /Users/rsutphin/ruby/surveyor/lib/surveyor/surveyor_controller_methods.rb:102:in `block (2 levels) in update'
  actionpack (3.2.6) lib/action_controller/metal/mime_responds.rb:196:in `call'
  actionpack (3.2.6) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
  /Users/rsutphin/ruby/surveyor/lib/surveyor/surveyor_controller_methods.rb:91:in `update'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.6) lib/active_support/callbacks.rb:425:in `_run__999653305408923731__process_action__2129288115063682050__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/params_wrapper.rb:206:in `process_action'
  activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.6) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.6) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.6) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:36:in `call'
```

The PUT body is

```
authenticity_token=%2BV10qw9oqya2v%2FjQaGfJcoKW5yPw1w39z6l0Mv6yfc0%3D&r%5B1%5D%5Banswer_id%5D=161
```

**Comment by rsutphin** [comment]
Verified that this is a regression from 0.22.0. It is not ruby version or rails version dependent (tested on 1.9.3 and REE; Rails 3.2.6 and 3.1.6).

The immediate cause seems to be that `question_id` is no longer being sent for grid questions.

**Comment by rsutphin** [comment]
Note also that this only affects AJAX updating — the full POSTs that are triggered when switching sections do properly store grid responses. This is why the cucumber feature passes.
