### ISSUE TITLE
Assets not pre-compiled on heroku

### ISSUE THREAD

**Issue by sweded** [NUARIG/surveyor#352]
I have a surveyor application with the kitchen sink survey running locally without issue. Deploying to heroku throws a 500 error `ActionView::Template::Error (surveyor_all.css isn't precompiled):`. I'm using surveyor (0.23.0.pre) and postgreSQL 9.1 on Rails 3.2.6. The asset pipeline is enabled in application.rb, `config.assets.enabled = true`

```
2012-07-30T20:20:43+00:00 app[web.1]: Started GET "/surveys" for 208.100.165.32 at 2012-07-30 20:20:43 +0000
2012-07-30T20:20:43+00:00 app[web.1]: Processing by SurveyorController#new as HTML
2012-07-30T20:20:43+00:00 app[web.1]:   Rendered vendor/bundle/ruby/1.9.1/bundler/gems/surveyor-e0d74ed80e4c/app/views/surveyor/new.html.haml within layouts/surveyor_default (0.3ms)
2012-07-30T20:20:43+00:00 app[web.1]: Completed 500 Internal Server Error in 5ms
2012-07-30T20:20:43+00:00 app[web.1]: 
2012-07-30T20:20:43+00:00 app[web.1]: ActionView::Template::Error (surveyor_all.css isn't precompiled):
2012-07-30T20:20:43+00:00 app[web.1]:     4: <head>
2012-07-30T20:20:43+00:00 app[web.1]:     5:   <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
2012-07-30T20:20:43+00:00 app[web.1]:     6:   <title>Survey: <%= controller.action_name %></title>
2012-07-30T20:20:43+00:00 app[web.1]:     7:   <%= surveyor_includes %>
2012-07-30T20:20:43+00:00 app[web.1]:     8: </head>
2012-07-30T20:20:43+00:00 app[web.1]:     9: <body>
2012-07-30T20:20:43+00:00 app[web.1]:     10:   <%= yield %>
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/sprockets/helpers/rails_helper.rb:142:in `digest_for'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/sprockets/helpers/rails_helper.rb:150:in `rewrite_asset_path'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_view/asset_paths.rb:27:in `compute_public_path'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/sprockets/helpers/rails_helper.rb:56:in `asset_path'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/sprockets/helpers/rails_helper.rb:49:in `block in stylesheet_link_tag'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/sprockets/helpers/rails_helper.rb:43:in `collect'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/sprockets/helpers/rails_helper.rb:43:in `stylesheet_link_tag'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/bundler/gems/surveyor-e0d74ed80e4c/lib/surveyor/helpers/surveyor_helper_methods.rb:11:in `surveyor_includes'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/bundler/gems/surveyor-e0d74ed80e4c/app/views/layouts/surveyor_default.html.erb:7:in `_vendor_bundle_ruby_______bundler_gems_surveyor_e_d__ed__e_c_app_views_layouts_surveyor_default_html_erb___1812780816183795121_37422340'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_view/template.rb:145:in `block in render'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/notifications.rb:125:in `instrument'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_view/template.rb:143:in `render'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_view/renderer/template_renderer.rb:18:in `render'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_view/renderer/renderer.rb:36:in `render_template'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_view/renderer/renderer.rb:17:in `render'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/rendering.rb:110:in `_render_template'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/streaming.rb:225:in `_render_template'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/rendering.rb:103:in `render_to_body'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/rendering.rb:88:in `render'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/rendering.rb:16:in `render'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
2012-07-30T20:20:43+00:00 app[web.1]:   /usr/local/lib/ruby/1.9.1/benchmark.rb:310:in `realtime'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/core_ext/benchmark.rb:5:in `ms'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
2012-07-30T20:20:43+00:00 heroku[router]: GET dry-escarpment-9528.herokuapp.com/surveys dyno=web.1 queue=0 wait=0ms service=14ms status=500 bytes=643
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/instrumentation.rb:39:in `render'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/base.rb:167:in `process_action'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:425:in `_run__10531091161903580__process_action__1625828833399298922__callbacks'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/callbacks.rb:17:in `process_action'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/notifications.rb:123:in `block in instrument'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/notifications.rb:123:in `instrument'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/params_wrapper.rb:206:in `process_action'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/base.rb:121:in `process'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/abstract_controller/rendering.rb:45:in `process'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal.rb:203:in `dispatch'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_controller/metal.rb:246:in `block in action'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:73:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:36:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:600:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/etag.rb:23:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/conditionalget.rb:25:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/head.rb:14:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/flash.rb:242:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/cookies.rb:338:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/query_cache.rb:64:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `_run__438731857645099351__call__1141147709115628540__callbacks'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/rack/logger.rb:26:in `call_app'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/rack/logger.rb:16:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/request_id.rb:22:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/runtime.rb:17:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/lock.rb:15:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/middleware/static.rb:62:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/engine.rb:479:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/application.rb:220:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/content_length.rb:14:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/rack/log_tailer.rb:17:in `call'
2012-07-30T20:20:43+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/handler/webrick.rb:59:in `service'
2012-07-30T20:20:43+00:00 app[web.1]:   /usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
2012-07-30T20:20:43+00:00 app[web.1]:   /usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
2012-07-30T20:20:43+00:00 app[web.1]:   /usr/local/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```

**Comment by jefflunt** [comment]
Just checking: did you compile and commit your assets before pushing to Heroku?

`bundle exec rake assets:precompile`

If so, try adding `config.assets.precompile += %w( [the surveyor assets in question] )` to your `config/production.rb` file, and tell me what happens.

**Comment by sweded** [comment]
I hadn't previously precompiled before pushing to Heroku but I went ahead and did so and added `config.assets.precompile += %w( surveyor_all.css )` to config/production.rb. The results are the same as before.

**Comment by jefflunt** [comment]
It fails on exactly the same file, not another one in surveyor?

**Comment by sweded** [comment]
Yes, same file. `2012-07-30T21:48:40+00:00 app[web.1]: ActionView::Template::Error (surveyor_all.css isn't precompiled):`

**Comment by jefflunt** [comment]
Can you put your kitchen sink app as-is on github, and post the link? I can try to deploy it to heroku later in the week and see what I can see.

**Comment by sweded** [comment]
https://github.com/sweded/surveyor-heroku

Thanks for taking a look. I'm having similar issues deploying other apps using surveyor. I set this one up last week to be vanilla as possible.

**Comment by jefflunt** [comment]
Sorry for the delay, I only got to this first thing this morning.

So, I've forked the project you linked to. I've also added you as a collaborator on the project, so go to town on the repo if you like: https://github.com/normalocity/surveyor-heroku 

You can see the commits I made to get it running on heroku, but basically all I did was:
- Added a default route and view
- Built the assets
- Pushed to heroku (app URL: http://sheltered-reef-9225.herokuapp.com/) on [their cedar stack](https://devcenter.heroku.com/articles/cedar/)
- On heroku, it's running Ruby 1.9.2 p290, and Rails 3.2.6

The basics seem to work - the app starts, and I'm not seeing any assets-related errors in the log. If you go to the app URL, you'll just see a boring page with a default message to confirm that the app is working.

Here's the output of the `heroku info` command

```
$ heroku info
=== sheltered-reef-9225
Addons:        Shared Database 5MB
Database Size: (empty)
Git URL:       git@heroku.com:sheltered-reef-9225.git
Owner Email:   jefflunt@gmail.com
Repo Size:     14M
Slug Size:     19M
Stack:         cedar
Web URL:       http://sheltered-reef-9225.herokuapp.com/
```

Here's the log output from heroku when I started the app:

```
2012-08-06T14:14:45+00:00 app[web.1]: => Booting WEBrick
2012-08-06T14:14:45+00:00 app[web.1]: => Rails 3.2.6 application starting in production on http://0.0.0.0:29820
2012-08-06T14:14:45+00:00 app[web.1]: => Call with -d to detach
2012-08-06T14:14:45+00:00 app[web.1]: => Ctrl-C to shutdown server
2012-08-06T14:14:45+00:00 app[web.1]: Connecting to database specified by DATABASE_URL
2012-08-06T14:14:46+00:00 app[web.1]: [2012-08-06 14:14:46] INFO  WEBrick 1.3.1
2012-08-06T14:14:46+00:00 app[web.1]: [2012-08-06 14:14:46] INFO  ruby 1.9.2 (2011-07-09) [x86_64-linux]
2012-08-06T14:14:46+00:00 app[web.1]: [2012-08-06 14:14:46] INFO  WEBrick::HTTPServer#start: pid=2 port=29820
2012-08-06T14:14:46+00:00 heroku[web.1]: State changed from starting to up
2012-08-06T14:14:47+00:00 app[web.1]: 
2012-08-06T14:14:47+00:00 app[web.1]: 
2012-08-06T14:14:47+00:00 app[web.1]: Started GET "/" for 165.124.223.165 at 2012-08-06 14:14:47 +0000
2012-08-06T14:14:47+00:00 app[web.1]: Processing by ApplicationController#index as HTML
2012-08-06T14:14:47+00:00 app[web.1]:   Rendered application/index.html within layouts/application (0.3ms)
2012-08-06T14:14:47+00:00 app[web.1]: Completed 200 OK in 52ms (Views: 52.0ms | ActiveRecord: 0.0ms)
2012-08-06T14:14:47+00:00 heroku[router]: GET sheltered-reef-9225.herokuapp.com/ dyno=web.1 queue=0 wait=1ms service=148ms status=200 bytes=494
2012-08-06T14:14:47+00:00 heroku[router]: GET sheltered-reef-9225.herokuapp.com/assets/application-3e2e13a08f81df23293bdf9cba06e6d9.css dyno=web.1 queue=0 wait=0ms service=12ms status=200 bytes=32929
2012-08-06T14:14:47+00:00 heroku[router]: GET sheltered-reef-9225.herokuapp.com/assets/application-79c25b64b7eee3e97bbb19013264c527.js dyno=web.1 queue=0 wait=0ms service=44ms status=200 bytes=431708
2012-08-06T14:14:48+00:00 heroku[router]: GET sheltered-reef-9225.herokuapp.com/favicon.ico dyno=web.1 queue=0 wait=0ms service=4ms status=200 bytes=0
```

**Comment by jefflunt** [comment]
Oh, I take that back. Tried to add the kitchen sink survey, and it broke the way you said. Okay, so I'll try to take a look into this more tonight and I'll get back to you.

**Comment by jibblett** [comment]
i'm also seeing this with rails 3.2.7 in production.  all the standard manipulation of asset config fails to get the surveyor assets recognized, though they seem to be getting compiled.

**Comment by jefflunt** [comment]
The only way I could get it working on heroku currently is to force runtime compilation. Look at the two most recent commits on https://github.com/normalocity/surveyor-heroku/commits/master - anytime Rails would run into an "...is not precompiled error" it compiles the asset in question on demand. This can cause increased page load times the first time a given asset is needed, but it should work.

Regarding the two most recent commits on my fork of your project: the second most recent commit references a heroku support article that explains the asset pipeline options on heroku's cedar stack when using Rails 3.1+. I've already tried precompiling (before pushing to heroku) which we know fails. I also tried not precompiling and waiting for heroku to compile them when the slug is compiled. That task ran when I pushed to heroku, and there were no errors in that step, but I still ran into the "...is not precompiled" error.

So, finally I just changed `environments/production.rb` to force compilation in real time: `config.assets.compile = true`

Setting this option in your production environment is a little undesirable on heroku when your app is running on the free tier, because they will spin down your app's dyno when the app goes idle for a while. This means, I believe, that the assets have to be compiled twice: on the first request immediately after a fresh push to heroku, and possibly again every time the dyno is spun back up after going idle. There are ways around letting the dyno go idle, but this is a hack at best.

Just to be clear, assets do not get compiled on _every_ request, just the first time a given asset is required after a dyno starts. Once compilation is successful, they should not need to be compiled again until either the dyno restarts, or you push an update to your app.

**Comment by jefflunt** [comment]
If the asset in question _does_ appear to be getting compiled locally, then I guess I would recommend taking this up with heroku support to ask if there are any extra things you need to do to get assets working when those assets are provided by a 3rd party gem. There may be no difference whatsoever, but it wouldn't hurt to ask.

They should be able to at least point you in the right direction, and if they say tell you to go back to the gem provider, you can ask them where we should look in the gem for more information/direction to resolve it, and post that info here in this issue.

**Comment by sweded** [comment]
Originally I was letting heroku compile. It looks like `config.assets.compile` must be set to `true`? I agree that isn't ideal. Can you send me a pull request? 

Thanks again

**Comment by jfoy** [comment]
The surveyor artifacts aren't ending up on the precompilation list by default; we have to add them. This change solved the problem for me:

https://github.com/jfoy/foolscap-survey/commit/2414ee89bcfefaa1fdf197cd048a9f76972642ed

**Comment by jfoy** [comment]
Update: Heroku's deployment-time asset compilation works correctly with this change. To re-enable it, you have to remove the hand-compiled assets from git: `git rm -r public/assets` .

**Comment by jefflunt** [comment]
@sweded - The suggested change; does it work for you?

**Comment by sweded** [comment]
Indeed it [does](http://surveyor-heroku.dev/surveys/kitchen-sink-survey/NE88e3rdNs/take). Even though I was previously pointed me towards `production.rb`,  I only [specified](https://github.com/NUBIC/surveyor/issues/352#issuecomment-7382746) the css since that was what I interpreted at issue. It would be helpful to have a note in the docs.

**Comment by jefflunt** [comment]
Cool, I'll see what I can do about the docs.

**Comment by rsutphin** [comment]
Could we just arrange for this:

> `config.assets.precompile += %w(surveyor_all.js surveyor_all.css)`

To be added to an initializer when you run `rake surveyor`? Automatic beats documentation. The only reason I can see to not make this automatic is if there is a reason why you'd ever _not_ add surveyor's assets to the precompilation list. I'm not an asset pipeline expert; is there a reason you'd only want to do this in production?

**Comment by jefflunt** [comment]
Hm...I think that will be okay. Not everyone will use the asset pipeline, but this shouldn't affect them if they're not using it. I'll read up on this option and confirm whether or not this only affects pre-compilation. If so, we might be fine to add this to surveyor.

**Comment by rsutphin** [comment]
> To be added to an initializer when you run `rake surveyor`?

By which I meant, of course, "when you run `rails g surveyor:install`".

**Comment by yoon** [comment]
@rsutphin So, when you run `rails g surveyor:install`  you're saying that we should generate[1](http://guides.rubyonrails.org/generators.html#application)  `config.assets.precompile += %w(surveyor_all.js surveyor_all.css)` into `config/environments/production.rb`? I guess it can't hurt, but it toes the line between being prescriptive and being helpful.

**Comment by rsutphin** [comment]
> So, when you run rails g surveyor:install you're saying that we should generate `config.assets.precompile += %w(surveyor_all.js surveyor_all.css)` into `config/environments/production.rb`?

@yoon Not quite. I was suggesting that we would generate a separate initializer containing that line. My (admittedly hazy) understanding of the asset pipeline setup in Surveyor now is that, if you have the asset pipeline enabled, Surveyor will expect its assets to be part of the pipeline. It seems like adding the assets to the precompile list is necessary for asset precompilation to work, so it seems like Surveyor should make sure that happens (if it can). I don't think it's prescriptive because it won't do anything if you aren't pre-compiling assets (again, AFAIK).

**Comment by hannahwhy** [comment]
Adding the Surveyor assets (the individual assets, not the `all` aggregations) in an engine initializer would also be fine, as per https://github.com/yipdw/surveyor/blob/21930fc1c60bb8b9f47aeff7d02e0ff7f3c9d1bb/lib/surveyor/engine.rb.  (Usage of the aggregations would be fine too.)  The initializer code in context can be seen at https://github.com/NUBIC/surveyor/pull/315/files.

`Surveyor::Helpers::AssetPipeline#asset_pipeline_enabled?` has code to detect the presence and usage of the Rails asset pipeline, so the initializer may be safely run across Rails ~> 3.0 applications.

**Comment by yoon** [comment]
@rsutphin I'm not too strong with the asset pipeline, but I do think there are other ways of using it than precompiling in production, e.g. http://guides.rubyonrails.org/asset_pipeline.html#live-compilation

If precompilation is the convention in the Rails world outside of Heroku as well, then your suggestion seems to be the way to go. But if it isn't, then surveyor would be extending a little too far. Anyone know?

**Comment by rsutphin** [comment]
@yoon, I don't believe that appending to `config.assets.precompile` _forces_ precompilation. It merely adds to the list of things that will be precompiled if you choose to precompile. If you don't separately take the action to precompile, then it has no effect.

**Comment by joshuap** [comment]
Hey so what's the verdict on this? I'm deploying with capistrano, and running the precompile task before every deploy. I have `config.assets.precompile += %w(surveyor_all.js surveyor_all.css)` in application.rb, but I was still getting the "surveyor_all.css isn't precompiled" error. The only way I'm getting it to work is by setting `config.assets.compile = true`, which I would like to avoid if possible.

**Comment by yoon** [comment]
@joshuap are you using heroku? Or are you precompiling by hand, or not at all? `config.assets.precompile += %w(surveyor_all.js surveyor_all.css)` seemed to fix this for @jfoy and @sweded 

The verdict is that we'll add `config.assets.precompile += %w(surveyor_all.js surveyor_all.css)` to an initializer that is generated by surveyor.

**Comment by joshuap** [comment]
@yoon I'm using heroku, and letting it run the precompile task during deployment. I have the assets.precompile setting configured, but it still wasn't compiling those assets for some reason. I'll have to revisit this in 2013 (about to leave for vacation). Thanks for the quick reply, and apologies for my not-so-quick response :).

**Comment by jefflunt** [comment]
I'm not sure if this will help your specific case, but there's a pretty
bare bones version of a surveyor app deployed on heroku here for
demonstration purposes:
http://surveyor-heroku.herokuapp.com/surveys

...and an open source repo for it here:
https://github.com/normalocity/surveyor-heroku

I used it for a training session to explain the asset pipeline and some of
its issues, while deploying to Heroku. So, long as Heroku maintains a free
tier it will pretty much exist as a reference.

It's deployed to the `cedar` stack with auto-asset compilation and such.
