### ISSUE TITLE
"question" is not a valid constant name!

### ISSUE THREAD

**Issue by yubrew** [NUARIG/surveyor#412]
I'm trying out the kitchen sink survey, and I'm not sure what is causing the error. I added "surveyor" to Gemlist and followed the install instructions. Attempting to run `bundle exec rake surveyor FILE=surveys/kitchen_sink_survey.rb` gave me an error.

`Rails 3.2.11`
`ruby 1.9.3p374`

I included the full trace, which might give some more hints.

```
bundle exec rake surveyor FILE=surveys/kitchen_sink_survey.rb --trace
** Invoke surveyor (first_time)
** Invoke surveyor:parse (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute surveyor:parse
--- Parsing /Users/username/sample_app/surveys/kitchen_sink_survey.rb ---
survey "Kitchen Sink survey", {:default_mandatory=>false}
  survey_section "Basic questions"
    question "These questions are examples of the basic supported input types"
    question "What is your favorite color?", {:pick=>:one}
    answer "red"
    answer "blue"
    answer "green"
    answer "yellow"
    answer :other
    question_2 "Choose the colors you don't like", {:pick=>:any}
    answer_1 "red"
    answer_2 "blue"
    answer_3 "green"
    answer_4 "yellow"
    answer :omit
    question_2a "Please explain why you don't like this color?"
    answer_1 "explanation", :text, {:help_text=>"Please give an explanation for each color you don't like"}
    dependency {:rule=>"A or B or C or D"}
    dependency_condition_A :q_2, "==", :a_1
rake aborted!
"question" is not a valid constant name!
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/surveyor-1.2.0/lib/surveyor/parser.rb:59:in `instance_eval'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/active_scaffold-3.2.0/lib/active_scaffold/extensions/reverse_associations.rb:34:in `block in autodetect_inverse'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/active_scaffold-3.2.0/lib/active_scaffold/extensions/reverse_associations.rb:26:in `each'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/active_scaffold-3.2.0/lib/active_scaffold/extensions/reverse_associations.rb:26:in `autodetect_inverse'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/active_scaffold-3.2.0/lib/active_scaffold/extensions/reverse_associations.rb:15:in `inverse_of_with_autodetect'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/associations/association.rb:212:in `inverse_reflection_for'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/associations/association.rb:217:in `invertible_for?'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/associations/association.rb:108:in `set_inverse_instance'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:353:in `add_to_target'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:495:in `block in concat_records'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:493:in `each'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:493:in `concat_records'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/associations/collection_association.rb:132:in `concat'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/activerecord-3.2.11/lib/active_record/associations/collection_proxy.rb:116:in `<<'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/surveyor-1.2.0/lib/surveyor/parser.rb:305:in `parse_and_build'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/surveyor-1.2.0/lib/surveyor/parser.rb:76:in `method_missing'
(eval):35:in `block (2 levels) in parse'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/surveyor-1.2.0/lib/surveyor/parser.rb:80:in `instance_eval'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/surveyor-1.2.0/lib/surveyor/parser.rb:80:in `method_missing'
(eval):6:in `block in parse'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/surveyor-1.2.0/lib/surveyor/parser.rb:80:in `instance_eval'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/surveyor-1.2.0/lib/surveyor/parser.rb:80:in `method_missing'
(eval):4:in `parse'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/surveyor-1.2.0/lib/surveyor/parser.rb:59:in `instance_eval'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/surveyor-1.2.0/lib/surveyor/parser.rb:59:in `parse'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/surveyor-1.2.0/lib/surveyor/parser.rb:16:in `parse'
/Users/username/.rvm/gems/ruby-1.9.3-p374/gems/surveyor-1.2.0/lib/tasks/surveyor_tasks.rake:10:in `block (2 levels) in <top (required)>'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:228:in `call'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:228:in `block in execute'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:223:in `each'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/Users/username/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:187:in `block in invoke_prerequisites'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:185:in `each'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:185:in `invoke_prerequisites'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:165:in `block in invoke_with_call_chain'
/Users/username/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/application.rb:143:in `invoke_task'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/application.rb:101:in `each'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/application.rb:110:in `run_with_threads'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/application.rb:73:in `block in run'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/lib/rake/application.rb:70:in `run'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/bin/rake:19:in `load'
/Users/username/.rvm/gems/ruby-1.9.3-p374@global/bin/rake:19:in `<main>'
/Users/username/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in `eval'
/Users/username/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => surveyor => surveyor:parse
```

**Comment by rsutphin** [comment]
Please ask general usage questions on the mailing list.
