### ISSUE TITLE
install generator fails in rails 4.1

### ISSUE THREAD

**Issue by KarlGl** [NUARIG/surveyor#481]
When trying to run the install generator I get the following error about formtastic:

/Users/kg/.rvm/gems/ruby-2.1.2/gems/surveyor-0.20.0/lib/formtastic/surveyor_builder.rb:3:in `<module:Formtastic>': uninitialized constant Formtastic::SemanticFormBuilder (NameError)
    from /Users/kg/.rvm/gems/ruby-2.1.2/gems/surveyor-0.20.0/lib/formtastic/surveyor_builder.rb:2:in`<top (required)>'
    from /Users/kg/.rvm/gems/ruby-2.1.2/gems/surveyor-0.20.0/lib/surveyor.rb:3:in `require'

**Comment by francescob** [comment]
put 
<code> gem 'surveyor', :github => "NUBIC/surveyor", :branch => "master" </code>

in your gem file

**Comment by taiwoayanleye** [comment]
Did same
gem 'surveyor', :git => 'git://github.com/NUBIC/surveyor.git', :branch => 'simple_form'
