### ISSUE TITLE
undefined method `question_group='

### ISSUE THREAD

**Issue by albertpak** [NUARIG/surveyor#492]
I'm running Rails 4.2, Ruby 2.1.3

When I try to run `rake surveyor FILE=surveys/kitchen_sink_survey.rb`, I get the following error:

```
rake surveyor FILE=surveys/kitchen_sink_survey.rb --trace
** Invoke surveyor (first_time)
** Invoke surveyor:parse (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute surveyor:parse
--- Parsing /surveys/kitchen_sink_survey.rb ---
survey "Kitchen Sink survey", {:default_mandatory=>false}
  survey_section "Basic questions"
    question "These questions are examples of the basic supported input types"
rake aborted!
NoMethodError: undefined method `question_group=' for #<Question:0x007fcb72138338>
/bundler/gems/surveyor-d4fe8df2586b/lib/surveyor/parser.rb:65:in `instance_eval'
/bundler/gems/surveyor-d4fe8df2586b/lib/surveyor/parser.rb:282:in `parse_and_build'
/bundler/gems/surveyor-d4fe8df2586b/lib/surveyor/parser.rb:82:in `method_missing'
(eval):8:in `block (2 levels) in parse'
/bundler/gems/surveyor-d4fe8df2586b/lib/surveyor/parser.rb:86:in `instance_eval'
/bundler/gems/surveyor-d4fe8df2586b/lib/surveyor/parser.rb:86:in `method_missing'
(eval):6:in `block in parse'
/bundler/gems/surveyor-d4fe8df2586b/lib/surveyor/parser.rb:86:in `instance_eval'
/bundler/gems/surveyor-d4fe8df2586b/lib/surveyor/parser.rb:86:in `method_missing'
(eval):4:in `parse'
/bundler/gems/surveyor-d4fe8df2586b/lib/surveyor/parser.rb:65:in `instance_eval'
/bundler/gems/surveyor-d4fe8df2586b/lib/surveyor/parser.rb:65:in `parse'
/bundler/gems/surveyor-d4fe8df2586b/lib/surveyor/parser.rb:22:in `parse'
/bundler/gems/surveyor-d4fe8df2586b/lib/surveyor/parser.rb:15:in `parse_file'
/bundler/gems/surveyor-d4fe8df2586b/lib/tasks/surveyor_tasks.rake:10:in `block (2 levels) in <top (required)>'
/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/xander/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/xander/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/bin/rake:23:in `load'
/bin/rake:23:in `<main>'
/bin/ruby_executable_hooks:15:in `eval'
/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => surveyor => surveyor:parse
```

Any idea how to get this gem to work?

**Comment by yoon** [comment]
For now, try the simple_form branch
